# -*- coding: utf-8 -*-
"""data _analyst.app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SLFCmjT78q2B8s6zZ6XmORqByLbbETtT
"""
import streamlit as st

st.set_page_config(page_title="Bansari Patel | Data Analyst", layout="wide")

st.title("👩‍💻 Bansari Patel")
st.subheader("Data Analyst | Python • SQL • ML")

st.write("---")

st.header("About Me")
st.write("""
I am a Data Analyst with internship experience at TEJASKP AI SOFTWARE.
I work on data cleaning, visualization, dashboards, and machine learning.
""")

st.header("Skills")
st.write("""
- Python (Pandas, NumPy)
- SQL
- Excel
- Power BI
- Machine Learning
""")

st.header("Projects")

st.subheader("Customer Segmentation")
st.write("""
- K-Means clustering
- Customer behavior analysis
- Business insights
""")

st.subheader("Jio Hotstar Data Analysis")
st.write("""
- Tools & Technologies:**
- Python (Pandas, Matplotlib)
- SQL (User activity & watch history analysis)
- Data Visualization
""")

st.header("Contact")
st.write("📧 Email: patelbansarijitendrakumar@gmail.com @email.com")
st.write("💻 GitHub: github.com/yourusername")

st.write("---")
st.write("© 2026 Bansari Patel")

