# -*- coding: utf-8 -*-
"""requirement.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1appsnVVdaJ9799E37M88g6JMH5uA7OSY
"""
install streamlit
import streamlit

